r"""Shapley Value attribution (PRD RF3.5).

Channels are the *players* of a cooperative game. The value of a coalition
``S`` is the number of conversions generated by converting paths whose channel
set is contained in ``S`` (i.e. the conversions still realisable if only the
channels in ``S`` were available). The Shapley value of each channel is its
average marginal contribution across all orderings of the players:

    phi_i = SUM_{S subset N\{i}} [|S|!(|N|-|S|-1)! / |N|!] * [v(S u {i}) - v(S)]

This satisfies the Shapley axioms (PRD RF3.5): efficiency (sum phi = total
conversions), symmetry, null player and additivity. Revenue is attributed
proportionally to conversion credit.

Note (PRD risk R2): the exact computation is O(2^|N|); for the GA sample the
number of distinct channels is small (~8), so exact evaluation is affordable.
"""

from __future__ import annotations

import itertools
import logging
import math
from collections import Counter

import pandas as pd

from src.models.base import AttributionModel, build_output, journey_sequences

logger = logging.getLogger("attribution.shapley")


def _coalition_values(paths: list[list[str]], converted: list[bool]) -> Counter[frozenset[str]]:
    """Count conversions per distinct channel-set (coalition) of converting paths."""
    coalitions: Counter[frozenset[str]] = Counter()
    for path, is_converted in zip(paths, converted, strict=True):
        if is_converted and path:
            coalitions[frozenset(path)] += 1
    return coalitions


def _coalition_worth(coalitions: Counter[frozenset[str]], coalition: frozenset[str]) -> float:
    """v(S): conversions of all converting paths whose channel-set is within ``S``."""
    return float(sum(count for members, count in coalitions.items() if members <= coalition))


def _shapley_values(coalitions: Counter[frozenset[str]], players: list[str]) -> dict[str, float]:
    """Exact Shapley values for each player given the coalition worth function."""
    n = len(players)
    if n == 0:
        return {}
    shapley: dict[str, float] = {player: 0.0 for player in players}
    factorials = [math.factorial(k) for k in range(n + 1)]

    for player in players:
        others = [p for p in players if p != player]
        for size in range(len(others) + 1):
            weight = factorials[size] * factorials[n - size - 1] / factorials[n]
            for subset in itertools.combinations(others, size):
                without = frozenset(subset)
                with_player = without | {player}
                marginal = _coalition_worth(coalitions, with_player) - _coalition_worth(
                    coalitions, without
                )
                shapley[player] += weight * marginal
    return shapley


class ShapleyValueModel(AttributionModel):
    """Shapley Value attribution from marginal channel contributions (RF3.5)."""

    def __init__(self) -> None:
        super().__init__("shapley")

    def attribute(self, journeys: pd.DataFrame) -> pd.DataFrame:
        paths, converted, revenues = journey_sequences(journeys)
        total_conversions = float(sum(converted))
        total_revenue = float(sum(r for r, c in zip(revenues, converted, strict=True) if c))
        channels = sorted({channel for path in paths for channel in path})

        if total_conversions <= 0 or not channels:
            return build_output({}, {}, channels)

        coalitions = _coalition_values(paths, converted)
        shapley = _shapley_values(coalitions, channels)
        credited = sum(shapley.values())
        logger.info(
            "shapley.computed players=%d credited=%.4f total_conversions=%.4f",
            len(channels),
            credited,
            total_conversions,
        )

        conversions: dict[str, float] = {}
        revenue: dict[str, float] = {}
        for channel in channels:
            share = shapley.get(channel, 0.0) / total_conversions if total_conversions else 0.0
            conversions[channel] = shapley.get(channel, 0.0)
            revenue[channel] = share * total_revenue
        return build_output(conversions, revenue, channels)


__all__: tuple[str, ...] = ("ShapleyValueModel",)
